"""The tracked sample must agree with the code that claims to have produced it.

``data/sample-data/clean_products.ndjson`` is the README's answer to "what does
this tool emit". Nothing read it. It drifted for roughly seven months and
eighteen commits to ``src/`` and ``config/`` in silence, and the drift did not
begin with neglect: the sample committed in "Fixed pricing for olive oil, and
cleaned-up the description text" records ``source=serving`` and
``bucket=oils_fats`` for the olive oil, and *that commit's own code* can produce
neither. It was generated from a working copy and committed alongside a later
one, so the commit specifically about fixing olive-oil pricing shipped a sample
that did not show the fix. A documentation surface that no test reads is a claim
nobody checks.

Why re-derivation, and not the alternatives
-------------------------------------------
**Not a regeneration diff.** Regenerating and comparing is the complete check and
it cannot be the gate: it needs the Open Food Facts JSONL export and the taxonomy
snapshot, neither of which is in this repository or reachable from a GitHub
runner. This project declares exactly one CI job, ``python -m pytest tests/ -v``.
A check that cannot run there is not a gate, so regeneration stays a documented
local step (README, "Regenerating it") and this module gates what CI can reach.

**Not a re-baselined snapshot.** Storing a copy of the file and diffing it
against itself passes by construction. It would have been green through every one
of those eighteen commits.

**Not shape alone.** A "fields present, types right" check is cheap and would
have caught the missing ``category_path``, ``margin`` and ``popularity`` — and it
would have stayed green on the olive-oil pricing drift, which is the failure this
issue is actually named after. It is one arm here, not the whole gate.

**Re-derivation.** Everything the extractor *computes* rather than reads is a
deterministic function of values the emitted document itself carries. Price,
pricing bucket, the unit-price debug string, margin, the margin breakdown and
popularity are all recomputed here by calling the extractor's own functions
against ``config/pricing_buckets.json`` — the same code and the same config a run
would use, with no dump and no taxonomy. The assertion's content comes from the
code, so it moves when the code moves and stays still when the code does not.
That is what makes it able to fail on a sample generated by an older working
copy.

What this module covers
-----------------------
* **Derived values** — ``price``, ``margin``, ``popularity``, ``currency``, and
  the five ``attrs`` entries that record how they were derived, all recomputed
  and compared exactly.
* **Shape** — the document's top-level field set, ``attrs`` value types (``str``
  or list of ``str``, never a joined string; see ``test_attrs_list_shape.py``),
  ``attr_keys`` equal to the sorted ``attrs`` keys, ``category_path`` as a single
  cumulative root-to-leaf chain, ``taxonomy_tags[0]`` equal to
  ``attrs["Category"]``, and every path segment present in ``taxonomy_tags`` so
  the two fields join on string as the schema table promises.
* **The rendered description tail** — the "Key specifications" run is rebuilt
  from the record's own ``attrs`` through ``build_description``. This is the arm
  that catches a *hand edit*: the drift was partly propagated by patching the
  file in place (a key renamed here, a value replaced there), and an in-place
  edit that touches ``attrs`` without re-rendering the description leaves the two
  disagreeing.
* **The recorded command** — the regeneration command in the README is parsed by
  the extractor's *own* ``build_parser``, so a renamed or deleted flag fails here
  rather than when someone next tries to follow the instructions. The record
  cannot rot silently either.

What this module cannot see
---------------------------
Every field that is *read* from the dump rather than computed from what the
document already carries: ``title``, ``brand``, ``image_url``, the ingredient
text inside ``description``, and the ``attrs`` entries sourced from the raw
record (``Quantity``, ``Serving size``, ``Nutri-Score``, ``NOVA group``,
``Eco-Score``, ``Allergens``, ``Labels``, ``Ingredients analysis``, ``Countries``
and the nutrition values). It also cannot see the *membership and labelling* of
``taxonomy_tags`` and ``category_path`` — the tag cap, the curation rules, the
anchoring, and the taxonomy display labels all need the taxonomy snapshot. It
checks that those two fields are internally well-formed and mutually consistent,
not that they name the right categories.

Concretely: the January-to-August drift in this sample had eight causes, and this
gate would have caught five of them (``category_path`` appearing, the business
signals appearing, the ``source=serving`` unit-price strings, the ``oils_fats`` /
``beverages_soft`` bucket assignments, and the prices that moved with them). It
would have missed the three that are relabelling and cap changes: ``Plant based
foods`` becoming ``Plant-based foods``, ``ravioli`` becoming ``Ravioli``, and the
flat tag list growing past three values. Those need a regeneration to detect. The
gate is partial, and it is partial in a direction that is stated rather than
discovered later.

Not-inert proof
---------------
``fixtures/stale_tracked_sample.json`` holds three records taken verbatim from
this very file as the repository shipped it at ``e81402b`` — the last state of
the sample before #57 regenerated it. :func:`test_stale_sample_fails_the_derived_value_arm`
and :func:`test_stale_sample_fails_the_shape_arm` require the gate to reject
them, and name which fields. A gate that has never been shown failing is an
assertion about itself.
"""

from __future__ import annotations

import json
import shlex
from pathlib import Path
from typing import Any, Dict, List, Mapping

import pytest

from off_demo_extract.extract import (
    MARGIN_SOURCE_STAMP,
    POPULARITY_SOURCE_STAMP,
    build_description,
    build_parser,
    derive_margin,
    derive_popularity,
)
from off_demo_extract.pricing import estimate_price, load_pricing_config

REPO_ROOT = Path(__file__).resolve().parents[1]
SAMPLE = REPO_ROOT / "data" / "sample-data" / "clean_products.ndjson"
PRICING_CONFIG = REPO_ROOT / "config" / "pricing_buckets.json"
README = REPO_ROOT / "README.md"
STALE_FIXTURE = Path(__file__).resolve().parent / "fixtures" / "stale_tracked_sample.json"

PRICE_SOURCE_STAMP = "estimated_unit_model"

TOP_LEVEL_FIELDS: Dict[str, Any] = {
    "id": str,
    "title": str,
    "brand": str,
    "description": str,
    "image_url": str,
    "price": float,
    "margin": int,
    "popularity": int,
    "currency": str,
    "taxonomy_tags": list,
    "category_path": list,
    "attrs": dict,
    "attr_keys": list,
    "dietary_restrictions": list,
}


def _load_sample() -> List[Dict[str, Any]]:
    text = SAMPLE.read_text(encoding="utf-8")
    records = [json.loads(line) for line in text.splitlines() if line.strip()]
    assert records, f"{SAMPLE} holds no records; every check below would be vacuous"
    return records


def _load_stale() -> List[Dict[str, Any]]:
    fixture = json.loads(STALE_FIXTURE.read_text(encoding="utf-8"))
    records = fixture["records"]
    assert records, "the stale fixture is empty; the not-inert proof would be vacuous"
    return records


def _label_tags(attrs: Mapping[str, Any]) -> List[str]:
    """Reconstruct the ``labels_tags`` the run priced with, from ``attrs["Labels"]``.

    ``build_attrs`` writes ``Labels`` through ``clean_tags(..., prefix_strip="en:")``,
    which strips an ``en:`` prefix and changes nothing else — order and duplicates
    included. Re-adding the prefix is therefore exact for every English tag, and
    both the pricing premiums and the margin uplifts are keyed on English tags
    only. A tag that arrived under another language keeps its own prefix through
    the strip and gains a second one here, which matches no key either way, so the
    reconstruction cannot invent a premium the run did not apply.
    """
    return [f"en:{value}" for value in (attrs.get("Labels") or [])]


def _derived_value_violations(record: Mapping[str, Any]) -> List[str]:
    """Recompute every value the extractor derives, and report each disagreement.

    Reads only the record itself and ``config/pricing_buckets.json``. No dump, no
    taxonomy, no network — which is what lets this run as an ordinary test.
    """
    config = load_pricing_config(PRICING_CONFIG)
    attrs = record.get("attrs")
    if not isinstance(attrs, dict):
        return ["attrs is missing or is not an object, so nothing can be re-derived"]

    label_tags = _label_tags(attrs)
    violations: List[str] = []

    price, bucket, unit_debug = estimate_price(
        gtin=record.get("id", ""),
        primary_category=attrs.get("Category") or "",
        categories=record.get("taxonomy_tags") or [],
        quantity=attrs.get("Quantity"),
        serving_size=attrs.get("Serving size"),
        labels_tags=label_tags,
        brand=record.get("brand") or "",
        config=config,
        title=record.get("title"),
    )
    margin, margin_detail = derive_margin(bucket, label_tags)

    expected: Dict[str, Any] = {
        "price": price,
        "margin": margin,
        "currency": config.currency,
    }
    for field, want in expected.items():
        if field not in record:
            violations.append(f"{field} is absent; a current run writes it")
        elif record[field] != want:
            violations.append(f"{field}: sample has {record[field]!r}, code derives {want!r}")

    expected_attrs: Dict[str, Any] = {
        "Price source": PRICE_SOURCE_STAMP,
        "Pricing bucket": bucket,
        "Estimated unit price": unit_debug,
        "Margin source": MARGIN_SOURCE_STAMP,
        "Modelled margin": margin_detail,
        "Popularity source": POPULARITY_SOURCE_STAMP,
    }
    for key, want in expected_attrs.items():
        if key not in attrs:
            violations.append(f"attrs[{key!r}] is absent; a current run writes it")
        elif attrs[key] != want:
            violations.append(f"attrs[{key!r}]: sample has {attrs[key]!r}, code derives {want!r}")

    scans = attrs.get("Unique scans (Open Food Facts)")
    if scans is None:
        violations.append("attrs['Unique scans (Open Food Facts)'] is absent; a current run writes it")
    elif "popularity" not in record:
        violations.append("popularity is absent; a current run writes it")
    else:
        want_popularity = derive_popularity(int(scans))
        if record["popularity"] != want_popularity:
            violations.append(
                f"popularity: sample has {record['popularity']!r}, "
                f"code derives {want_popularity!r} from {scans!r} scans"
            )

    return violations


def _shape_violations(record: Mapping[str, Any]) -> List[str]:
    """Report every way the document departs from the emitted shape."""
    violations: List[str] = []

    for field, want_type in TOP_LEVEL_FIELDS.items():
        if field not in record:
            violations.append(f"top-level field {field!r} is absent")
        elif want_type is float:
            if not isinstance(record[field], (int, float)) or isinstance(record[field], bool):
                violations.append(f"{field} is {type(record[field]).__name__}, expected a number")
        elif want_type is int:
            if not isinstance(record[field], int) or isinstance(record[field], bool):
                violations.append(f"{field} is {type(record[field]).__name__}, expected int")
        elif not isinstance(record[field], want_type):
            violations.append(
                f"{field} is {type(record[field]).__name__}, expected {want_type.__name__}"
            )

    extra = sorted(set(record) - set(TOP_LEVEL_FIELDS))
    if extra:
        violations.append(f"top-level fields no current run writes: {extra}")

    attrs = record.get("attrs")
    if not isinstance(attrs, dict):
        return violations

    for key, value in attrs.items():
        if isinstance(value, list):
            if not value:
                violations.append(f"attrs[{key!r}] is an empty list; the writer omits the key instead")
            if not all(isinstance(item, str) for item in value):
                violations.append(f"attrs[{key!r}] holds a non-string element")
        elif not isinstance(value, str):
            violations.append(f"attrs[{key!r}] is {type(value).__name__}, expected str or list of str")

    if record.get("attr_keys") != sorted(attrs):
        violations.append("attr_keys is not the sorted attrs keys")

    tags = record.get("taxonomy_tags")
    if isinstance(tags, list) and tags and "Category" in attrs and tags[0] != attrs["Category"]:
        violations.append(
            f"taxonomy_tags[0] is {tags[0]!r} but attrs['Category'] is {attrs['Category']!r}; "
            "the primary category is the first flat tag"
        )

    path = record.get("category_path")
    if isinstance(path, list):
        if not path:
            violations.append("category_path is empty; the default gate drops such products")
        for i in range(1, len(path)):
            prefix = f"{path[i - 1]}/"
            if not path[i].startswith(prefix) or "/" in path[i][len(prefix):]:
                violations.append(
                    f"category_path is not one cumulative chain: {path[i]!r} does not extend "
                    f"{path[i - 1]!r} by exactly one segment"
                )
        if isinstance(tags, list):
            segments = {entry.split("/")[-1] for entry in path if isinstance(entry, str)}
            unjoinable = sorted(segments - set(tags))
            if unjoinable:
                violations.append(
                    f"category_path segments absent from taxonomy_tags, so the two do not "
                    f"join on string: {unjoinable}"
                )

    return violations


def _description_violations(record: Mapping[str, Any]) -> List[str]:
    """Rebuild the "Key specifications" tail from ``attrs`` and compare it."""
    attrs = record.get("attrs")
    description = record.get("description")
    if not isinstance(attrs, dict) or not isinstance(description, str):
        return ["description or attrs is missing, so the tail cannot be rebuilt"]

    rendered = build_description(title="", desc="", attrs=attrs, single_line=True)
    marker = "Key specifications: "
    if marker not in rendered:
        return [] if marker not in description else ["description carries a spec run that attrs cannot explain"]

    tail = rendered.split(marker, 1)[1]
    if not description.endswith(f"{marker}{tail}"):
        return [
            "the description's spec run disagrees with attrs; expected it to end with "
            f"{marker + tail!r}"
        ]
    return []


def _documented_command() -> List[str]:
    """Return the regeneration command recorded in the README, as an argv list."""
    text = README.read_text(encoding="utf-8")
    heading = "### Regenerating it"
    assert heading in text, (
        f"{README.name} no longer records how the sample is regenerated. "
        "That command is the only thing that makes the file reproducible."
    )
    after = text.split(heading, 1)[1]
    fence = "```bash"
    assert fence in after, f"no bash block follows {heading!r} in {README.name}"
    block = after.split(fence, 1)[1].split("```", 1)[0]
    return shlex.split(block.replace("\\\n", " "))


# ----------------------------
# The current sample
# ----------------------------


def test_every_derived_value_in_the_sample_is_what_the_code_derives() -> None:
    """Recomputed price, bucket, margin and popularity match the tracked file.

    This is the arm the "Fixed pricing for olive oil" drift needed. The olive oil
    in that sample recorded ``bucket=oils_fats``; the classifier that commit
    shipped returns ``olive_oil`` for it.
    """
    failures = {
        record.get("id"): violations
        for record in _load_sample()
        if (violations := _derived_value_violations(record))
    }
    assert not failures, (
        "the tracked sample disagrees with the code that derives these values. "
        "Regenerate it (README, 'Regenerating it') rather than editing it:\n"
        + json.dumps(failures, indent=2)
    )


def test_the_sample_has_the_shape_a_current_run_emits() -> None:
    failures = {
        record.get("id"): violations
        for record in _load_sample()
        if (violations := _shape_violations(record))
    }
    assert not failures, (
        "the tracked sample's shape is not the shape a current run emits:\n"
        + json.dumps(failures, indent=2)
    )


def test_the_sample_descriptions_agree_with_their_own_attrs() -> None:
    failures = {
        record.get("id"): violations
        for record in _load_sample()
        if (violations := _description_violations(record))
    }
    assert not failures, (
        "a description does not match the attrs it is rendered from, which is what "
        "an in-place edit of the sample looks like:\n" + json.dumps(failures, indent=2)
    )


# ----------------------------
# The recorded command
# ----------------------------


def test_the_readme_records_a_command_the_extractor_still_accepts() -> None:
    """Every flag in the recorded command exists on the extractor's own parser.

    #47 had to reconstruct this command from the shape of the output and from
    ``git log``. Recording it is only half the fix: a recorded command that no
    longer parses sends the next reader back to the archaeology.
    """
    argv = _documented_command()
    assert argv[:4] == ["uv", "run", "-m", "off_demo_extract.extract"], (
        f"the recorded command does not invoke the extractor: {argv[:4]}"
    )

    unused = Path("unused")
    parser = build_parser(unused, unused, unused, unused)
    args = parser.parse_args(argv[4:])

    assert args.output == Path("data/sample-data/clean_products.ndjson"), (
        f"the recorded command writes {args.output}, not the tracked sample"
    )
    assert args.lang == "en"
    assert args.require_category
    assert args.yes, "without --yes the command stops on a prompt when the sample already exists"
    assert args.report.parts[:2] != ("data", "sample-data"), (
        "the recorded command writes its report into the tracked sample directory, "
        "which leaves an untracked file behind after every regeneration"
    )


def test_the_recorded_record_count_is_the_number_of_records_tracked() -> None:
    """``--max-output-records`` and the file agree, so neither can drift alone."""
    args = build_parser(*[Path("unused")] * 4).parse_args(_documented_command()[4:])
    assert args.max_output_records == len(_load_sample())


# ----------------------------
# The gate is not inert
# ----------------------------


def test_the_stale_fixture_is_the_file_this_repo_used_to_ship() -> None:
    """Guard the proof below against a fixture that stopped being stale data."""
    fixture = json.loads(STALE_FIXTURE.read_text(encoding="utf-8"))
    assert fixture["commit"] == "e81402b79ed2f3331adcef220308f292a29ed200"
    assert len(fixture["records"]) == 3
    ids = [record["id"] for record in fixture["records"]]
    assert ids == ["0000790200123", "0008112100281", "0008127000019"]


def test_stale_sample_fails_the_derived_value_arm() -> None:
    """The olive-oil drift the issue is named after, caught by re-derivation.

    Two of the three records are rejected on values they *carry*, not on values
    they are missing — so this arm is doing its own work and is not a restatement
    of the shape arm. The third is the control: its pricing was already current in
    January and re-derivation clears it, which is what stops this test from
    passing on a checker that simply rejects everything old.
    """
    by_id = {record["id"]: _derived_value_violations(record) for record in _load_stale()}

    olive_oil = " | ".join(by_id["0008127000019"])
    assert "'oils_fats'" in olive_oil and "'olive_oil'" in olive_oil, olive_oil
    assert "source=serving" in olive_oil, olive_oil

    sesame_oil = " | ".join(by_id["0008112100281"])
    assert "'beverages_soft'" in sesame_oil and "'oils_fats'" in sesame_oil, sesame_oil

    priced_wrong = [
        entry for entry in by_id["0008127000019"] if entry.startswith("price:")
    ]
    assert priced_wrong, "the drifted bucket must move the price too"

    control = by_id["0000790200123"]
    assert not [entry for entry in control if entry.startswith(("price:", "margin:", "attrs['Pricing bucket']", "attrs['Estimated unit price']"))], (
        "the control record's pricing was already current; an arm that rejects it "
        f"is rejecting age, not drift: {control}"
    )


def test_stale_sample_fails_the_shape_arm() -> None:
    """The fields that arrived after January are missing, and the arm names them."""
    for record in _load_stale():
        violations = " | ".join(_shape_violations(record))
        for field in ("category_path", "margin", "popularity"):
            assert f"top-level field {field!r} is absent" in violations, (
                f"{record['id']}: shape arm did not notice {field} was missing: {violations}"
            )


@pytest.mark.parametrize(
    "arm",
    [_derived_value_violations, _shape_violations],
    ids=["derived_values", "shape"],
)
def test_each_arm_clears_the_current_sample_and_rejects_the_stale_one(arm) -> None:
    """Both directions, per arm, in one place: green on current, red on stale."""
    assert not [violation for record in _load_sample() for violation in arm(record)]
    assert all(arm(record) for record in _load_stale())
